# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('gu', models.CharField(blank=True, max_length=4, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('update_time', models.IntegerField(blank=True, null=True)),
                ('time_ahead', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('temp', models.SmallIntegerField(blank=True, null=True)),
                ('day_high_temp', models.SmallIntegerField(blank=True, null=True)),
                ('day_low_temp', models.SmallIntegerField(blank=True, null=True)),
                ('sky_state', models.IntegerField(blank=True, null=True)),
                ('weather_state', models.IntegerField(blank=True, null=True)),
                ('weather_eng', models.CharField(blank=True, max_length=20, null=True)),
                ('rain_persent', models.IntegerField(blank=True, null=True)),
                ('expect_rain_6h', models.FloatField(blank=True, null=True)),
                ('expect_rain_12h', models.FloatField(blank=True, null=True)),
                ('expect_snow_6h', models.FloatField(blank=True, null=True)),
                ('expect_snow_12h', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_way', models.IntegerField(blank=True, null=True)),
                ('wind_text', models.CharField(blank=True, max_length=4, null=True)),
                ('humi', models.IntegerField(blank=True, null=True)),
                ('fine_dust', models.CharField(blank=True, max_length=10, null=True)),
                ('small_fine_dust', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
